[package]
name = "secreton-grpc"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "gRPC definitions and server implementation for Secreton"
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true

[dependencies]
tonic = { workspace = true, features = ["transport"] }
prost.workspace = true
tokio.workspace = true
secreton-common.workspace = true
futures-util.workspace = true

[build-dependencies]
tonic-build.workspace = true
protoc-bin-vendored = "3.0"
