//! Policy engine and parsing logic

use chrono::Utc;
use pest::Parser;
use pest_derive::Parser;
use std::collections::HashMap;
use uuid::Uuid;

use super::error::PolicyResult;
use secreton_errors::SecretonError;
use super::model::{
    ConditionOperator, Policy, PolicyCondition, PolicyEffect, PolicyRule, PolicyType,
};

/// Pest parser for policy language
#[derive(Parser)]
#[grammar = "policy_grammar.pest"]
pub struct PolicyParser;

/// Policy language grammar rules
/// This enum is generated by pest_derive from policy_grammar.pest

/// Policy engine for evaluating access control policies
#[derive(Clone)]
pub struct PolicyEngine {
    /// Compiled policies cache
    pub policies: HashMap<Uuid, CompiledPolicy>,
    /// Role hierarchy
    pub role_hierarchy: HashMap<Uuid, Vec<Uuid>>,
}

impl PolicyEngine {
    /// Create a new policy engine
    pub fn new() -> Self {
        Self {
            policies: HashMap::new(),
            role_hierarchy: HashMap::new(),
        }
    }

    /// Add or update a policy
    pub fn add_policy(&mut self, policy: &Policy) -> PolicyResult<()> {
        let compiled = self.compile_policy(policy)?;
        self.policies.insert(policy.id, compiled);
        Ok(())
    }

    /// Remove a policy
    pub fn remove_policy(&mut self, policy_id: &Uuid) -> PolicyResult<()> {
        self.policies.remove(policy_id);
        Ok(())
    }

    /// Add role hierarchy relationship
    pub fn add_role_relationship(&mut self, child_role: Uuid, parent_role: Uuid) {
        self.role_hierarchy
            .entry(child_role)
            .or_insert_with(Vec::new)
            .push(parent_role);
    }

    /// Compile a policy into executable form
    fn compile_policy(&self, policy: &Policy) -> PolicyResult<CompiledPolicy> {
        let mut compiled_rules = Vec::new();

        for rule in &policy.rules {
            let compiled_rule = self.compile_rule(rule)?;
            compiled_rules.push(compiled_rule);
        }

        Ok(CompiledPolicy {
            id: policy.id,
            effect: policy.effect.clone(),
            rules: compiled_rules,
        })
    }

    /// Compile a policy rule
    fn compile_rule(&self, rule: &PolicyRule) -> PolicyResult<CompiledRule> {
        let mut compiled_conditions = Vec::new();

        for condition in &rule.conditions {
            let compiled_condition = self.compile_condition(condition)?;
            compiled_conditions.push(compiled_condition);
        }

        Ok(CompiledRule {
            id: rule.id,
            actions: rule.actions.clone(),
            resources: rule.resources.clone(),
            conditions: compiled_conditions,
        })
    }

    /// Compile a policy condition
    fn compile_condition(&self, condition: &PolicyCondition) -> PolicyResult<CompiledCondition> {
        let operator = match condition.operator {
            ConditionOperator::Equals => ConditionOperator::Equals,
            ConditionOperator::NotEquals => ConditionOperator::NotEquals,
            ConditionOperator::Contains => ConditionOperator::Contains,
            ConditionOperator::NotContains => ConditionOperator::NotContains,
            ConditionOperator::In => ConditionOperator::In,
            ConditionOperator::NotIn => ConditionOperator::NotIn,
            ConditionOperator::GreaterThan => ConditionOperator::GreaterThan,
            ConditionOperator::LessThan => ConditionOperator::LessThan,
            ConditionOperator::Regex => ConditionOperator::Regex,
        };

        Ok(CompiledCondition {
            attribute: condition.attribute.clone(),
            operator,
            values: condition.values.clone(),
        })
    }

    /// Parse policy from string
    pub fn parse_policy(&self, policy_text: &str) -> PolicyResult<Policy> {
        let pairs = PolicyParser::parse(Rule::policy, policy_text)
            .map_err(|e| SecretonError::PolicyParseError { source: Box::new(e) })?;

        self.build_policy_from_pairs(pairs)
    }

    /// Build policy from parsed pairs
    fn build_policy_from_pairs(
        &self,
        mut pairs: pest::iterators::Pairs<Rule>,
    ) -> PolicyResult<Policy> {
        let pair = pairs
            .next()
            .ok_or_else(|| SecretonError::InvalidPolicySyntax {
                details: "Empty policy".to_string(),
            })?;

        let mut policy = Policy {
            id: Uuid::new_v4(),
            name: String::new(),
            policy_type: PolicyType::ABAC,
            effect: PolicyEffect::Allow,
            rules: Vec::new(),
            metadata: HashMap::new(),
            created_at: Utc::now(),
            updated_at: Utc::now(),
            enabled: true,
        };

        for inner_pair in pair.into_inner() {
            match inner_pair.as_rule() {
                Rule::policy_header => {
                    // Parse policy header (name, type, effect)
                    self.parse_policy_header(inner_pair, &mut policy)?;
                }
                Rule::rule_block => {
                    // Parse rule block
                    let rule = self.parse_rule_block(inner_pair)?;
                    policy.rules.push(rule);
                }
                _ => {}
            }
        }

        Ok(policy)
    }

    /// Parse policy header
    fn parse_policy_header(
        &self,
        pair: pest::iterators::Pair<Rule>,
        policy: &mut Policy,
    ) -> PolicyResult<()> {
        for inner_pair in pair.into_inner() {
            match inner_pair.as_rule() {
                Rule::identifier => {
                    policy.name = inner_pair.as_str().to_string();
                }
                Rule::string => {
                    if let Some(value) = self.parse_string(inner_pair) {
                        policy.name = value;
                    }
                }
                _ => {}
            }
        }
        Ok(())
    }

    /// Parse rule block
    fn parse_rule_block(&self, pair: pest::iterators::Pair<Rule>) -> PolicyResult<PolicyRule> {
        let mut rule = PolicyRule {
            id: Uuid::new_v4(),
            name: format!("rule_{}", Uuid::new_v4().simple()),
            conditions: Vec::new(),
            actions: Vec::new(),
            resources: Vec::new(),
        };

        for inner_pair in pair.into_inner() {
            match inner_pair.as_rule() {
                Rule::condition_block => {
                    let condition = self.parse_condition_block(inner_pair)?;
                    rule.conditions.push(condition);
                }
                Rule::identifier => {
                    // Parse actions/resources
                    let value = inner_pair.as_str().to_string();
                    if value.starts_with("action:") {
                        rule.actions.push(value[7..].to_string());
                    } else if value.starts_with("resource:") {
                        rule.resources.push(value[9..].to_string());
                    }
                }
                _ => {}
            }
        }

        Ok(rule)
    }

    /// Parse condition block
    fn parse_condition_block(
        &self,
        pair: pest::iterators::Pair<Rule>,
    ) -> PolicyResult<PolicyCondition> {
        let mut condition = PolicyCondition {
            attribute: String::new(),
            operator: ConditionOperator::Equals,
            values: Vec::new(),
        };

        for inner_pair in pair.into_inner() {
            match inner_pair.as_rule() {
                Rule::attribute => {
                    condition.attribute = inner_pair.as_str().to_string();
                }
                Rule::operator => {
                    condition.operator = self.parse_operator(inner_pair)?;
                }
                Rule::value_list => {
                    condition.values = self.parse_value_list(inner_pair)?;
                }
                _ => {}
            }
        }

        Ok(condition)
    }

    /// Parse operator
    fn parse_operator(&self, pair: pest::iterators::Pair<Rule>) -> PolicyResult<ConditionOperator> {
        match pair.as_str() {
            "==" => Ok(ConditionOperator::Equals),
            "!=" => Ok(ConditionOperator::NotEquals),
            "contains" => Ok(ConditionOperator::Contains),
            "not_contains" => Ok(ConditionOperator::NotContains),
            "in" => Ok(ConditionOperator::In),
            "not_in" => Ok(ConditionOperator::NotIn),
            ">" => Ok(ConditionOperator::GreaterThan),
            "<" => Ok(ConditionOperator::LessThan),
            "regex" => Ok(ConditionOperator::Regex),
            _ => Err(SecretonError::InvalidPolicyCondition {
                condition: format!("Unknown operator: {}", pair.as_str()),
            }),
        }
    }

    /// Parse value list
    fn parse_value_list(&self, pair: pest::iterators::Pair<Rule>) -> PolicyResult<Vec<String>> {
        let mut values = Vec::new();

        for inner_pair in pair.into_inner() {
            match inner_pair.as_rule() {
                Rule::string => {
                    if let Some(value) = self.parse_string(inner_pair) {
                        values.push(value);
                    }
                }
                Rule::number => {
                    values.push(inner_pair.as_str().to_string());
                }
                Rule::boolean => {
                    values.push(inner_pair.as_str().to_string());
                }
                _ => {}
            }
        }

        Ok(values)
    }

    /// Parse string value
    fn parse_string(&self, pair: pest::iterators::Pair<Rule>) -> Option<String> {
        let text = pair.as_str();
        if text.starts_with('"') && text.ends_with('"') {
            Some(text[1..text.len() - 1].to_string())
        } else {
            Some(text.to_string())
        }
    }
}

/// Compiled policy for efficient evaluation
#[derive(Debug, Clone)]
pub struct CompiledPolicy {
    pub id: Uuid,
    pub effect: PolicyEffect,
    pub rules: Vec<CompiledRule>,
}

/// Compiled rule
#[derive(Debug, Clone)]
pub struct CompiledRule {
    pub id: Uuid,
    pub actions: Vec<String>,
    pub resources: Vec<String>,
    pub conditions: Vec<CompiledCondition>,
}

/// Compiled condition
#[derive(Debug, Clone)]
pub struct CompiledCondition {
    pub attribute: String,
    pub operator: ConditionOperator,
    pub values: Vec<String>,
}
