//! OpenAPI document.
//!
//! The specification is generated by `utoipa` and served as JSON at
//! `/api-docs/openapi.json`. There is deliberately no bundled Swagger UI: the
//! `utoipa-swagger-ui` crate's build script downloads a zip from GitHub at compile time,
//! which breaks hermetic, offline and air-gapped builds — and in this repository it was
//! the reason `cargo check` failed outright. Point any viewer at the JSON, or vendor a
//! pinned UI asset under `crates/ui/public/` where it is served like any other file.

use axum::Json;
use utoipa::OpenApi;
use utoipa::openapi::security::{ApiKey, ApiKeyValue, HttpAuthScheme, HttpBuilder, SecurityScheme};
use utoipa::{Modify, openapi};

#[derive(OpenApi)]
#[openapi(
    info(
        title = "Secreton API",
        description = "Secrets management: KV v2, transit, PKI, SSH, database and TOTP engines.",
        license(name = "Apache-2.0", url = "https://www.apache.org/licenses/LICENSE-2.0"),
    ),
    servers((url = "/api/v1", description = "This server")),
    modifiers(&SecurityAddon),
    tags(
        (name = "auth", description = "Authentication and session management"),
        (name = "secret", description = "KV v2 secret engine"),
        (name = "transit", description = "Encryption as a service"),
        (name = "pki", description = "Certificate authority"),
        (name = "ssh", description = "SSH certificate signing"),
        (name = "database", description = "Dynamic database credentials"),
        (name = "totp", description = "Time-based one-time passwords"),
        (name = "sys", description = "Seal, unseal and system state"),
        (name = "admin", description = "Users, roles and policies"),
    ),
)]
pub struct ApiDoc;

struct SecurityAddon;

impl Modify for SecurityAddon {
    fn modify(&self, openapi: &mut openapi::OpenApi) {
        let Some(components) = openapi.components.as_mut() else {
            return;
        };
        // Both credential shapes the auth middleware accepts, so a generated client can
        // pick the one that fits: bearer for programmatic callers, cookie for browsers.
        components.add_security_scheme(
            "bearer",
            SecurityScheme::Http(
                HttpBuilder::new()
                    .scheme(HttpAuthScheme::Bearer)
                    .bearer_format("JWT")
                    .build(),
            ),
        );
        components.add_security_scheme(
            "session",
            SecurityScheme::ApiKey(ApiKey::Cookie(ApiKeyValue::new(
                crate::session::SESSION_COOKIE,
            ))),
        );
    }
}

pub async fn openapi_document() -> Json<openapi::OpenApi> {
    Json(ApiDoc::openapi())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_document_serialises_and_advertises_both_credential_shapes() {
        let doc = ApiDoc::openapi();
        let json = serde_json::to_value(&doc).expect("the spec must serialise");
        assert_eq!(json["info"]["title"], "Secreton API");

        let schemes = &json["components"]["securitySchemes"];
        assert_eq!(schemes["bearer"]["scheme"], "bearer");
        assert_eq!(schemes["session"]["in"], "cookie");
        assert_eq!(schemes["session"]["name"], crate::session::SESSION_COOKIE);
    }
}
