//! Username/password authentication method

use async_trait::async_trait;
use std::collections::HashMap;
use tokio::sync::RwLock;
use uuid::Uuid;
use chrono::Utc;
use argon2::Argon2;
use password_hash::{PasswordHash, PasswordVerifier};
use crate::model::*;
use crate::error::*;
use crate::service::*;

/// User/password authentication method
pub struct UserPassAuthMethod {
    enabled: bool,
    config: Option<AuthMethod>,
    users: RwLock<HashMap<String, UserEntry>>,
}

impl UserPassAuthMethod {
    pub fn new() -> Self {
        Self {
            enabled: false,
            config: None,
            users: RwLock::new(HashMap::new()),
        }
    }

    /// Add a user with hashed password
    pub async fn add_user(&self, username: String, password_hash: String, id: String, groups: Vec<String>, policies: Vec<String>) {
        let user_entry = UserEntry {
            username: username.to_string(),
            password_hash,
            id,
            groups,
            policies,
            metadata: HashMap::new(),
        };

        let mut users = self.users.write().await;
        users.insert(username, user_entry);
    }

    /// Verify password against hash
    fn verify_password(&self, password: &str, hash: &str) -> AuthMethodResult<bool> {
        let parsed_hash = PasswordHash::new(hash)
            .map_err(|_| AuthMethodError::InvalidCredentials("Invalid password hash format".to_string()))?;

        let argon2 = Argon2::default();
        Ok(argon2.verify_password(password.as_bytes(), &parsed_hash).is_ok())
    }

    /// Get user entry
    async fn get_user(&self, username: &str) -> Option<UserEntry> {
        let users = self.users.read().await;
        users.get(username).cloned()
    }
}

#[async_trait]
impl AuthMethodImpl for UserPassAuthMethod {
    fn method_type(&self) -> AuthMethodType {
        AuthMethodType::UserPass
    }

    async fn init(&mut self, config: &AuthMethod) -> AuthMethodResult<()> {
        self.config = Some(config.clone());
        self.enabled = true;
        Ok(())
    }

    async fn authenticate(&self, credentials: &AuthCredentials) -> AuthMethodResult<AuthResult> {
        if !self.is_enabled() {
            return Err(AuthMethodError::MethodDisabled);
        }

        match credentials {
            AuthCredentials::UserPass { username, password } => {
                if let Some(user_entry) = self.get_user(username).await {
                    if self.verify_password(password, &user_entry.password_hash)? {
                        let user_info = UserInfo {
                            username: user_entry.username.to_string(),
                            id: Uuid::new_v4(), // Generate new UUID since user_entry.id is String
                            groups: user_entry.groups.clone(),
                            metadata: user_entry.metadata.clone(),
                            email: None,
                            display_name: None,
                            created_at: Utc::now(),
                            last_login: Some(Utc::now()),
                        };

                        Ok(AuthResult {
                            authenticated: true,
                            user_info: Some(user_info),
                            policies: user_entry.policies.clone(),
                            lease_duration: None,
                            renewable: Some(true),
                            token: None, // Token will be generated by the service
                            accessor: None,
                            metadata: HashMap::new(),
                            mfa_required: false, // Could be extended for MFA
                            mfa_methods: Vec::new(),
                        })
                    } else {
                        Err(AuthMethodError::InvalidCredentials("Invalid username or password".to_string()))
                    }
                } else {
                    Err(AuthMethodError::InvalidCredentials("Invalid username or password".to_string()))
                }
            }
            _ => Err(AuthMethodError::InvalidCredentials("Unsupported credential type".to_string())),
        }
    }

    async fn validate_token(&self, _token: &str) -> AuthMethodResult<UserInfo> {
        // Token validation is handled by the token method
        Err(AuthMethodError::MethodNotSupported)
    }

    async fn revoke_token(&self, _token: &str) -> AuthMethodResult<()> {
        // Token revocation is handled by the token method
        Err(AuthMethodError::MethodNotSupported)
    }

    fn is_enabled(&self) -> bool {
        self.enabled
    }

    fn enable(&mut self) {
        self.enabled = true;
    }

    fn disable(&mut self) {
        self.enabled = false;
    }
}

/// User entry for userpass authentication
#[derive(Clone, Debug)]
pub struct UserEntry {
    pub username: String,
    pub password_hash: String,
    pub id: String,
    pub groups: Vec<String>,
    pub policies: Vec<String>,
    pub metadata: HashMap<String, String>,
}